# Build the image in multiple OS containers

name: workflow_8
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buil_push_docker_image:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: TuneDemo/rs_policy_service_actions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run : mvn -B package --file pom.xml          
